//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseServices.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can&apos;t be a cost that is lower or 0..
        /// </summary>
        internal static string ExpenseFormCostError {
            get {
                return ResourceManager.GetString("ExpenseFormCostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can&apos;t be an expense for the future..
        /// </summary>
        internal static string ExpenseFormDateError {
            get {
                return ResourceManager.GetString("ExpenseFormDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the expense can&apos;t be empty..
        /// </summary>
        internal static string ExpenseFormNameError {
            get {
                return ResourceManager.GetString("ExpenseFormNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or write the place of expense.
        /// </summary>
        internal static string ExpenseFormPlaceError {
            get {
                return ResourceManager.GetString("ExpenseFormPlaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or write the type of expense.
        /// </summary>
        internal static string ExpenseFormTypeError {
            get {
                return ResourceManager.GetString("ExpenseFormTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &quot;From&quot; can&apos;t be higher than the &quot;To&quot; date.
        /// </summary>
        internal static string ExpenseSearchDateError {
            get {
                return ResourceManager.GetString("ExpenseSearchDateError", resourceCulture);
            }
        }
    }
}
