<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpenseServices\ExpenseServices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\DataSources\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot" Version="5.1.58" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.58" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MessagesResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessagesResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MessagesResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MessagesResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>