//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date &quot;From&quot; can&apos;t be higher than the date &quot;To&quot;.
        /// </summary>
        internal static string ExpenseErrorMessageFilter {
            get {
                return ResourceManager.GetString("ExpenseErrorMessageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Expense.
        /// </summary>
        internal static string ExpenseFormTitleNew {
            get {
                return ResourceManager.GetString("ExpenseFormTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Expense.
        /// </summary>
        internal static string ExpenseFormTitleUpdate {
            get {
                return ResourceManager.GetString("ExpenseFormTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string ExpenseGroupBoxFilterTitle {
            get {
                return ResourceManager.GetString("ExpenseGroupBoxFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ExpenseLabelActionAdd {
            get {
                return ResourceManager.GetString("ExpenseLabelActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string ExpenseLabelActionBack {
            get {
                return ResourceManager.GetString("ExpenseLabelActionBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ExpenseLabelActionDelete {
            get {
                return ResourceManager.GetString("ExpenseLabelActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string ExpenseLabelActionModify {
            get {
                return ResourceManager.GetString("ExpenseLabelActionModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string ExpenseLabelCost {
            get {
                return ResourceManager.GetString("ExpenseLabelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ExpenseLabelDate {
            get {
                return ResourceManager.GetString("ExpenseLabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ExpenseLabelFilterAction {
            get {
                return ResourceManager.GetString("ExpenseLabelFilterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string ExpenseLabelFromInput {
            get {
                return ResourceManager.GetString("ExpenseLabelFromInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExpenseLabelName {
            get {
                return ResourceManager.GetString("ExpenseLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string ExpenseLabelPages {
            get {
                return ResourceManager.GetString("ExpenseLabelPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string ExpenseLabelPlace {
            get {
                return ResourceManager.GetString("ExpenseLabelPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ExpenseLabelTableAction {
            get {
                return ResourceManager.GetString("ExpenseLabelTableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string ExpenseLabelToInput {
            get {
                return ResourceManager.GetString("ExpenseLabelToInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExpenseLabelType {
            get {
                return ResourceManager.GetString("ExpenseLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense added succesfully.
        ///Do you wish do add another one?.
        /// </summary>
        internal static string ExpenseMessageAddAddSucess {
            get {
                return ResourceManager.GetString("ExpenseMessageAddAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExpenseMessageBoxTitleError {
            get {
                return ResourceManager.GetString("ExpenseMessageBoxTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ExpenseMessageBoxTitleSuccess {
            get {
                return ResourceManager.GetString("ExpenseMessageBoxTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this expense? 
        ///This action cannot be reversed..
        /// </summary>
        internal static string ExpenseMessageDeleteWarning {
            get {
                return ResourceManager.GetString("ExpenseMessageDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error..
        /// </summary>
        internal static string ExpenseMessageException {
            get {
                return ResourceManager.GetString("ExpenseMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expense searched does not exist..
        /// </summary>
        internal static string ExpenseMessageExpenseNotFound {
            get {
                return ResourceManager.GetString("ExpenseMessageExpenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense modified succesfully..
        /// </summary>
        internal static string ExpenseMessageUpdateSucess {
            get {
                return ResourceManager.GetString("ExpenseMessageUpdateSucess", resourceCulture);
            }
        }
    }
}
