//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where the expense file will be saved on.
        /// </summary>
        public static string ExpenseExportFileDialogTitle {
            get {
                return ResourceManager.GetString("ExpenseExportFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses_{0}.
        /// </summary>
        public static string ExpenseFileNameExpenses {
            get {
                return ResourceManager.GetString("ExpenseFileNameExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseReport_{0}.
        /// </summary>
        public static string ExpenseFileNameReport {
            get {
                return ResourceManager.GetString("ExpenseFileNameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of expenses.
        /// </summary>
        public static string ExpenseFormTitleListExpenses {
            get {
                return ResourceManager.GetString("ExpenseFormTitleListExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string ExpenseFormTitleMainMenu {
            get {
                return ResourceManager.GetString("ExpenseFormTitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Expense.
        /// </summary>
        public static string ExpenseFormTitleNew {
            get {
                return ResourceManager.GetString("ExpenseFormTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report of expenses.
        /// </summary>
        public static string ExpenseFormTitleReport {
            get {
                return ResourceManager.GetString("ExpenseFormTitleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings .
        /// </summary>
        public static string ExpenseFormTitleSettings {
            get {
                return ResourceManager.GetString("ExpenseFormTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Expense.
        /// </summary>
        public static string ExpenseFormTitleUpdate {
            get {
                return ResourceManager.GetString("ExpenseFormTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ExpenseGroupBoxFilterTitle {
            get {
                return ResourceManager.GetString("ExpenseGroupBoxFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ExpenseLabelActionAdd {
            get {
                return ResourceManager.GetString("ExpenseLabelActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ExpenseLabelActionBack {
            get {
                return ResourceManager.GetString("ExpenseLabelActionBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ExpenseLabelActionDelete {
            get {
                return ResourceManager.GetString("ExpenseLabelActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExpenseLabelActionExport {
            get {
                return ResourceManager.GetString("ExpenseLabelActionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ExpenseLabelActionFilter {
            get {
                return ResourceManager.GetString("ExpenseLabelActionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string ExpenseLabelActionModify {
            get {
                return ResourceManager.GetString("ExpenseLabelActionModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ExpenseLabelActionNext {
            get {
                return ResourceManager.GetString("ExpenseLabelActionNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ExpenseLabelActionPrevious {
            get {
                return ResourceManager.GetString("ExpenseLabelActionPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ExpenseLabelActionSave {
            get {
                return ResourceManager.GetString("ExpenseLabelActionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string ExpenseLabelCost {
            get {
                return ResourceManager.GetString("ExpenseLabelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ExpenseLabelCount {
            get {
                return ResourceManager.GetString("ExpenseLabelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ExpenseLabelDate {
            get {
                return ResourceManager.GetString("ExpenseLabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpenseLabelExpenses {
            get {
                return ResourceManager.GetString("ExpenseLabelExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string ExpenseLabelInputFrom {
            get {
                return ResourceManager.GetString("ExpenseLabelInputFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ExpenseLabelInputTo {
            get {
                return ResourceManager.GetString("ExpenseLabelInputTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ExpenseLabelLanguage {
            get {
                return ResourceManager.GetString("ExpenseLabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ExpenseLabelLanguageEnglish {
            get {
                return ResourceManager.GetString("ExpenseLabelLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string ExpenseLabelLanguageSpanish {
            get {
                return ResourceManager.GetString("ExpenseLabelLanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ExpenseLabelName {
            get {
                return ResourceManager.GetString("ExpenseLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string ExpenseLabelPages {
            get {
                return ResourceManager.GetString("ExpenseLabelPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses per page.
        /// </summary>
        public static string ExpenseLabelPageSize {
            get {
                return ResourceManager.GetString("ExpenseLabelPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string ExpenseLabelPlace {
            get {
                return ResourceManager.GetString("ExpenseLabelPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place with most expenses.
        /// </summary>
        public static string ExpenseLabelPlaceWithMostExpenses {
            get {
                return ResourceManager.GetString("ExpenseLabelPlaceWithMostExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string ExpenseLabelSummary {
            get {
                return ResourceManager.GetString("ExpenseLabelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ExpenseLabelTableAction {
            get {
                return ResourceManager.GetString("ExpenseLabelTableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ExpenseLabelTotal {
            get {
                return ResourceManager.GetString("ExpenseLabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ExpenseLabelType {
            get {
                return ResourceManager.GetString("ExpenseLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type with most expenses.
        /// </summary>
        public static string ExpenseLabelTypeWithMostExpenses {
            get {
                return ResourceManager.GetString("ExpenseLabelTypeWithMostExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string ExpenseLabelVersion {
            get {
                return ResourceManager.GetString("ExpenseLabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ExpenseMenuLabelClose {
            get {
                return ResourceManager.GetString("ExpenseMenuLabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ExpenseMenuLabelExpenseAdd {
            get {
                return ResourceManager.GetString("ExpenseMenuLabelExpenseAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ExpenseMenuLabelExpenseList {
            get {
                return ResourceManager.GetString("ExpenseMenuLabelExpenseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpenseMenuLabelExpenses {
            get {
                return ResourceManager.GetString("ExpenseMenuLabelExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ExpenseMenuLabelReports {
            get {
                return ResourceManager.GetString("ExpenseMenuLabelReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ExpenseMenuLabelSettings {
            get {
                return ResourceManager.GetString("ExpenseMenuLabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense added succesfully.
        ///Do you wish do add another one?.
        /// </summary>
        public static string ExpenseMessageAddSuccess {
            get {
                return ResourceManager.GetString("ExpenseMessageAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ExpenseMessageBoxTitleError {
            get {
                return ResourceManager.GetString("ExpenseMessageBoxTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ExpenseMessageBoxTitleSuccess {
            get {
                return ResourceManager.GetString("ExpenseMessageBoxTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ExpenseMessageBoxTitleWarning {
            get {
                return ResourceManager.GetString("ExpenseMessageBoxTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this expense? 
        ///This action cannot be reversed..
        /// </summary>
        public static string ExpenseMessageDeleteWarning {
            get {
                return ResourceManager.GetString("ExpenseMessageDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error..
        /// </summary>
        public static string ExpenseMessageException {
            get {
                return ResourceManager.GetString("ExpenseMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expense searched does not exist..
        /// </summary>
        public static string ExpenseMessageExpenseNotFound {
            get {
                return ResourceManager.GetString("ExpenseMessageExpenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses exported succesfully..
        /// </summary>
        public static string ExpenseMessageExportSuccess {
            get {
                return ResourceManager.GetString("ExpenseMessageExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You recently changed the language. 
        ///It will be applied after you close the program..
        /// </summary>
        public static string ExpenseMessageLanguageChanged {
            get {
                return ResourceManager.GetString("ExpenseMessageLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving over 100 expenses per page can lead to performance issues. 
        ///Are you sure you want to retrieve {0} expenses per page?.
        /// </summary>
        public static string ExpenseMessagePageChangeWarningOver100 {
            get {
                return ResourceManager.GetString("ExpenseMessagePageChangeWarningOver100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving 10 or less expenses per page can affect user experience. 
        ///Are you sure do you want to retrieve {0} expenses per page?.
        /// </summary>
        public static string ExpenseMessagePageChangeWarningUnder10 {
            get {
                return ResourceManager.GetString("ExpenseMessagePageChangeWarningUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t set that pages bring less than 1 expense..
        /// </summary>
        public static string ExpenseMessagePageSizeError {
            get {
                return ResourceManager.GetString("ExpenseMessagePageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense removed succesfuly..
        /// </summary>
        public static string ExpenseMessageRemoveSuccess {
            get {
                return ResourceManager.GetString("ExpenseMessageRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report exported sucessfully..
        /// </summary>
        public static string ExpenseMessageReportExportSuccess {
            get {
                return ResourceManager.GetString("ExpenseMessageReportExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings changed succesfully..
        /// </summary>
        public static string ExpenseMessageSettingsChangeSuccess {
            get {
                return ResourceManager.GetString("ExpenseMessageSettingsChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense modified succesfully..
        /// </summary>
        public static string ExpenseMessageUpdateSucess {
            get {
                return ResourceManager.GetString("ExpenseMessageUpdateSucess", resourceCulture);
            }
        }
    }
}
